"use client";
import "@/src/app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/src/components/Fragments/Navbar";
import Provider from "@/src/components/Fragments/Provider";
import Footer from "@/src/components/Fragments/Footer";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const queryClient = new QueryClient({
  defaultOptions: { queries: { refetchOnWindowFocus: false } },
});

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Toko Onlen",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <Provider>
            <Navbar initialCookies={null} />
            {children}
            <Footer />
          </Provider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
