import { Metadata } from "next";

type Props = {
  params: {
    profile: string
  }
}

// Generate Metadata with params
export const generateMetadata = async ({ params }: Props): Promise<Metadata> => {
  const title = await new Promise(resolve => {
    setTimeout(() => resolve(`${params.profile}`), 100);
  });
  return {
    title: `Edit ${title}`,
    description: 'Generated by create next app',
  }
}

export default function ChangeProfile({ params }: Props) {
  return (
      <h1>Product Details {params.profile}</h1>
  )
}